### ISSUE TITLE
Update guzzlehttp/psr7

### ISSUE THREAD

**Issue by jstolp** [CMTelecom/messaging-php#10]
Hello CMTelecom,

Could you provide a new version of the client with a newer version of _guzzlehttp/psr7_ 
currently the constraint is 1.4.* which is pretty old. I want to use the 1.6.x version for my project, but it conflicts with your constraint :(

Kind reagards,

J

**Comment by baspeters** [comment]
Thanks Jeroen for mentioning this. Since updating dependencies breaks the backward compatibility of PHP versions older than 7.2, I have released a [v2.0.0](https://github.com/CMTelecom/messaging-php/releases) that is specifically updated to the latest dependencies.

I do want to point out that this package has been deprecated for a while, and if you find the time, you should definitely look at the replacement package [here](https://github.com/cmdotcom/text-sdk-php)

**Comment by jstolp** [comment]
@baspeters didn't know about the new package. Will look into it! Thanks for the fast fix!
